### ISSUE TITLE
Outputs are not propagated to next steps

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/run-nix-shell#10]
**Describe the bug**
Outputs are not propagated to next steps

**To Reproduce**
```yaml
name: Whatever

on:
  workflow_dispatch:

jobs:
  whatever:
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@v4

      - name: a
        id: a
        uses: tweag/run-nix-shell@v0
        with:
          pure: false
          run: |
            echo "foo_bar=what" >> "$GITHUB_OUTPUT"

      - name: b
        id: b
        run: |
          echo "${{ steps.a.outputs.foo_bar }}"
```

**Expected behavior**
`what` should be displayed in the Github Action logs.
If we do the same thing **without** `tweag/run-nix-shell` then it works as expected.

**Environment**
 - OS name + version: NixOS 24.05pre-git
